-- MySQL Script generated by MySQL Workbench
-- Sun Oct  4 01:21:07 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema java07_shopping
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `java07_shopping` ;

-- -----------------------------------------------------
-- Schema java07_shopping
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `java07_shopping` DEFAULT CHARACTER SET utf8 ;
USE `java07_shopping` ;

-- -----------------------------------------------------
-- Table `java07_shopping`.`PhongBan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java07_shopping`.`PhongBan` ;

CREATE TABLE IF NOT EXISTS `java07_shopping`.`PhongBan` (
  `MaPB` INT NOT NULL,
  `TenPB` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`MaPB`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `java07_shopping`.`NhanVien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java07_shopping`.`NhanVien` ;

CREATE TABLE IF NOT EXISTS `java07_shopping`.`NhanVien` (
  `MaNV` INT NOT NULL,
  `HoTen` VARCHAR(255) NOT NULL,
  `SoDienThoai` VARCHAR(255) NOT NULL,
  `DiaChi` TEXT NOT NULL,
  `NgaySinh` DATE NOT NULL,
  `GioiTinh` BIT NOT NULL,
  `MaPB` INT NOT NULL,
  PRIMARY KEY (`MaNV`),
  INDEX `FK_NhanVien_PhongBan_idx` (`MaPB` ASC) VISIBLE,
  CONSTRAINT `FK_NhanVien_PhongBan`
    FOREIGN KEY (`MaPB`)
    REFERENCES `java07_shopping`.`PhongBan` (`MaPB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `java07_shopping`.`LoaiHang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java07_shopping`.`LoaiHang` ;

CREATE TABLE IF NOT EXISTS `java07_shopping`.`LoaiHang` (
  `MaLoai` INT NOT NULL,
  `TenLoai` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`MaLoai`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `java07_shopping`.`MatHang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java07_shopping`.`MatHang` ;

CREATE TABLE IF NOT EXISTS `java07_shopping`.`MatHang` (
  `MaMH` INT NOT NULL,
  `TenMH` VARCHAR(255) NOT NULL,
  `GiaMua` FLOAT NOT NULL,
  `GiaBan` FLOAT NOT NULL,
  `MauSac` VARCHAR(255) NOT NULL,
  `KichCo` VARCHAR(30) NOT NULL,
  `MoTa` TEXT NULL,
  `SoLuong` INT NOT NULL,
  `MaLoai` INT NOT NULL,
  PRIMARY KEY (`MaMH`),
  INDEX `fk_MatHang_LoaiHang1_idx` (`MaLoai` ASC) VISIBLE,
  CONSTRAINT `FK_MatHang_LoaiHang`
    FOREIGN KEY (`MaLoai`)
    REFERENCES `java07_shopping`.`LoaiHang` (`MaLoai`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `java07_shopping`.`KhachHang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java07_shopping`.`KhachHang` ;

CREATE TABLE IF NOT EXISTS `java07_shopping`.`KhachHang` (
  `MaKH` INT NOT NULL,
  `TenKH` VARCHAR(255) NOT NULL,
  `SoDienThoai` VARCHAR(255) NOT NULL,
  `DiaChi` TEXT NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `TaiKhoan` VARCHAR(30) NOT NULL,
  `MatKhau` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`MaKH`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `java07_shopping`.`LHTT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java07_shopping`.`LHTT` ;

CREATE TABLE IF NOT EXISTS `java07_shopping`.`LHTT` (
  `MaLHTT` INT NOT NULL,
  `MoTa` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`MaLHTT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `java07_shopping`.`TTDH`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java07_shopping`.`TTDH` ;

CREATE TABLE IF NOT EXISTS `java07_shopping`.`TTDH` (
  `MaTTDH` INT NOT NULL,
  `MoTa` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`MaTTDH`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `java07_shopping`.`DonHang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java07_shopping`.`DonHang` ;

CREATE TABLE IF NOT EXISTS `java07_shopping`.`DonHang` (
  `MaDH` INT NOT NULL,
  `DiaChiGiaoHang` TEXT NOT NULL,
  `SoDTGiaoHang` VARCHAR(255) NOT NULL,
  `NgayDatHang` DATE NOT NULL,
  `MaLHTT` INT NOT NULL,
  `MaKH` INT NOT NULL,
  PRIMARY KEY (`MaDH`),
  INDEX `fk_DonHang_LHTT1_idx` (`MaLHTT` ASC) VISIBLE,
  INDEX `fk_DonHang_KhachHang1_idx` (`MaKH` ASC) VISIBLE,
  CONSTRAINT `FK_DonHang_LHTT`
    FOREIGN KEY (`MaLHTT`)
    REFERENCES `java07_shopping`.`LHTT` (`MaLHTT`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_DonHang_KhachHang`
    FOREIGN KEY (`MaKH`)
    REFERENCES `java07_shopping`.`KhachHang` (`MaKH`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `java07_shopping`.`HoaDon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java07_shopping`.`HoaDon` ;

CREATE TABLE IF NOT EXISTS `java07_shopping`.`HoaDon` (
  `MaHD` INT NOT NULL,
  `NgayXuat` DATETIME NOT NULL DEFAULT current_timestamp,
  `PhiVanChuyen` FLOAT NOT NULL,
  `TongTien` FLOAT NOT NULL,
  `MaDH` INT NOT NULL,
  PRIMARY KEY (`MaHD`),
  INDEX `fk_HoaDon_DonHang1_idx` (`MaDH` ASC) VISIBLE,
  CONSTRAINT `FK_HoaDon_DonHang`
    FOREIGN KEY (`MaDH`)
    REFERENCES `java07_shopping`.`DonHang` (`MaDH`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `java07_shopping`.`GiaoHang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java07_shopping`.`GiaoHang` ;

CREATE TABLE IF NOT EXISTS `java07_shopping`.`GiaoHang` (
  `MaDH` INT NOT NULL,
  `MaTTDH` INT NOT NULL,
  `ThoiGian` DATETIME NULL DEFAULT current_timestamp,
  PRIMARY KEY (`MaDH`, `MaTTDH`),
  INDEX `fk_DonHang_has_TTDH_TTDH1_idx` (`MaTTDH` ASC) VISIBLE,
  INDEX `fk_DonHang_has_TTDH_DonHang1_idx` (`MaDH` ASC) VISIBLE,
  CONSTRAINT `FK_GiaoHang_DonHang`
    FOREIGN KEY (`MaDH`)
    REFERENCES `java07_shopping`.`DonHang` (`MaDH`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_GiaoHang_TTDH`
    FOREIGN KEY (`MaTTDH`)
    REFERENCES `java07_shopping`.`TTDH` (`MaTTDH`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `java07_shopping`.`XuLyDonHang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `java07_shopping`.`XuLyDonHang` ;

CREATE TABLE IF NOT EXISTS `java07_shopping`.`XuLyDonHang` (
  `MaDH` INT NOT NULL,
  `MaMH` INT NOT NULL,
  `SoLuong` INT NOT NULL,
  PRIMARY KEY (`MaDH`, `MaMH`),
  INDEX `fk_DonHang_has_MatHang_MatHang1_idx` (`MaMH` ASC) VISIBLE,
  INDEX `fk_DonHang_has_MatHang_DonHang1_idx` (`MaDH` ASC) VISIBLE,
  CONSTRAINT `FK_XuLyDonHang_DonHang`
    FOREIGN KEY (`MaDH`)
    REFERENCES `java07_shopping`.`DonHang` (`MaDH`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_XuLyDonHang_MatHang`
    FOREIGN KEY (`MaMH`)
    REFERENCES `java07_shopping`.`MatHang` (`MaMH`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
